### ISSUE TITLE
not found:  * ~\content

### ISSUE THREAD

**Issue by alexeiaccio** [nuxt-community/content-template#11]
Hello, I have the same error with nuxtent-template, and also with nuxtent-module\examples\markdown-components. At the dev & generate modes.

>  ERROR  Failed to compile with 1 errors                                                                         12:44:41

> This dependency was not found:

>  ~\content in ./.nuxt/plugins.markdownComponents.3312f6eb.js

> To install it, you can run: npm install --save ~\content

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c12">#c12</a>)</em></sub></div>

**Comment by alidcast** [comment]
Related to https://github.com/nuxt-community/nuxtent-module/issues/78. Will be fixed in next release.
