### ISSUE TITLE
500 Network error trying to view /hello-world

### ISSUE THREAD

**Issue by levibostian** [nuxt-community/content-template#2]
How to reproduce:

```
vue init nuxt-community/nuxtent-starter my-site
cd my-site
npm install
npm run dev
```

Go to `localhost:3000` in browser and click on "See your first post". I get a 500 error Nuxt network error page:

<img width="769" alt="screen shot 2017-07-24 at 7 49 19 am" src="https://user-images.githubusercontent.com/2041082/28524051-a1632376-7044-11e7-8173-5fee679d3354.png">

The terminal output not very helpful indicating no errors:

<img width="385" alt="screen shot 2017-07-24 at 7 50 20 am" src="https://user-images.githubusercontent.com/2041082/28524109-cda6fbf6-7044-11e7-952d-751e1cc4dc29.png">

Console also not super helpful to help debug issue:

<img width="1275" alt="screen shot 2017-07-24 at 7 50 58 am" src="https://user-images.githubusercontent.com/2041082/28524134-e50e6b58-7044-11e7-9658-322d4f931eb3.png">

I did not make any modifications to the project once I generated it via the vue-cli. 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c4">#c4</a>)</em></sub></div>

**Comment by alidcast** [comment]
This seems related to https://github.com/nuxt-community/nuxtent/issues/17. Are you using Windows?

**Comment by levibostian** [comment]
Actually, no, I am using MacOS.  npm -v = 5.3.0, node -v = v6.9.1

**Comment by alidcast** [comment]
Why does it say it rendered `content/helloworld` in terminal, if route takes you to `hello-world`?

Also, what does it show if you go to `content-api/hello-world` endpoint?

**Comment by levibostian** [comment]
*Why does it say it rendered content/helloworld in terminal, if route takes you to hello-world?* 

That must be my bad. While I was learning nuxtent, I may have gone to that path myself in the browser thinking that was where to go and view the content. After I have gone back to the project, started up a new terminal session, a new browser session, and I started up the app, that entry in the terminal does not show up. That must have been me manually browsing there. 

*Also, what does it show if you go to content-api/hello-world endpoint?*

```
{"meta":{"fileName":"HelloWorld.comp.md","section":"/","dirName":"/","filePath":"/private/tmp/my-site/content/HelloWorld.comp.md"},"date":"07-24-2017","permalink":"/hello-world","anchors":[],"title":"Hello World","body":{"relativePath":"./HelloWorld.comp.md"}}
```

**Comment by alidcast** [comment]
Ok, so it's not a problem with the `serverMiddleware` since the data is there.

When you click the router link, it takes you to what url? 

What does `localhost:3000/hello-world` show? 

It seems that your nuxt site is opening  at `127.0.0.1:3000` which might be the problem. 

Maybe try setting `api baseURL`:

```
module.exports = {
  api: {
    baseURL: (isProd) => isProd ? 'https://production-url.com' : `https://127.0.0.1:3000` 
  }
}

```

**Comment by xemoka** [comment]
Yeah, I think this is the same "CORS problem" with `127.0.0.1` vs `localhost` as the host.

Accessing via localhost:3000, changing the baseURL or settings a `HOST` env variable should help. That `Open http://127.0.0.1:3000` throws you off -> printed before that is your output showing the content-api address as localhost.

**Comment by alidcast** [comment]
@xemoka You were able to get it working?

**Comment by levibostian** [comment]
Yup. Changing the `baseURL` to 127.0.0.1 over localhost did the trick:

Looks like the only thing I had to change from the template project is changing this:

```
  api: {
    baseURL: (isProd) => isProd ? 'http://localhost:3000' : 'http://localhost:3000'
  }
```

to this:

```
  api: {
    baseURL: (isProd) => isProd ? 'http://localhost:3000' : 'http://127.0.0.1:3000'
  }
```

in `nuxtent.config.js`.
