### ISSUE TITLE
update template to latest nuxtent version

### ISSUE THREAD

**Issue by ghost** [nuxt-community/content-template#3]
Hi,

When I generate static with the command `yarn generate`, I am able to access to the main page but I can't access to https://mydomain.com/hello-world, it's only work in dev with `yarn run dev` http://myipvps:3000/hello-world

my nuxtent.config.js :

```
module.exports = {
  content: {
    permalink: ':slug',
    routes: [
      {
        path: '/_content',
        method: 'get'
      }
    ],
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'https://mydomain.com'
      : 'http://myipvps:3000'
  }
}
```

my package.json : 
```
{
  "name": "stnetwork",
  "version": "1.0.0",
  "description": "Nuxtjs Buefy",
  "author": "",
  "private": true,
  "dependencies": {
    "nuxtent": "latest",
    "nuxt": "1.0.0-alpha.3",
    "@nuxtjs/axios": "latest"
  },
  "scripts": {
    "dev": "HOST=myipvps nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "deploy": "push-dir --dir=dist --branch=gh-pages --cleanup",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.15.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.1",
    "eslint-plugin-standard": "^2.0.1"
  }
}
```

http://myipvps:3000/hello-world , that works
https://mydomain.com, that works
https://mydomain.com/hello-world, doesn't work (404 Page not found, nginx)

Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c3">#c3</a>)</em></sub></div>

**Comment by alidcast** [comment]
Hi, thanks for opening this issue. The api changed and I will need to update the template. Will do that soon. You can look at docs for updated information.

**Comment by alidcast** [comment]
@STnetwork Template is updated!
