### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by hackuun** [nuxt-community/content-template#4]
If you go to this page and update it, content is gone - https://nuxtent-template.now.sh/hello-world

Is it just broken demo, or issue with Nuxtent?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c1">#c1</a>)</em></sub></div>

**Comment by alidcast** [comment]
Related to other issue you posted #5, and already opened issue #3.
