### ISSUE TITLE
Template is broken

### ISSUE THREAD

**Issue by hackuun** [nuxt-community/content-template#5]
Hello. Awful starting experience I have.
First I notice bug in demo.
Then I tried to use starter locally, and it instantly throws me an error.

```
Nuxt.js Error:

Error: render function or template not defined in component: anonymous
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c2">#c2</a>)</em></sub></div>

**Comment by hackuun** [comment]
This didn't help me https://github.com/nuxt-community/nuxtent-template/issues/2

**Comment by alidcast** [comment]
Related to #3. Still need to update demo  to latest version. But the documantation is updated and you can use that as reference

**Comment by hackuun** [comment]
Where exactly in docs I can't find it?

**Comment by alidcast** [comment]
https://nuxtent.now.sh/guide/configuration

**Comment by hackuun** [comment]
I was asking regarding yo this specific issue. I saw that site. Where I can find info how to fix this

**Comment by alidcast** [comment]
@iamdubx demo has been updated :) It only needed a modification to `nuxtent.config` to match slight API change.

**Comment by alidcast** [comment]
If you experience any problems feel free to open up a new issue but please don't do so with anger or entitlement, thanks

**Comment by hackuun** [comment]
@alidcastano I feel bad, sorry mate! Looks like I started in bad time. 
I appreciate your support, and sorry once again.

**Comment by alidcast** [comment]
@iamdubx No worries, thanks for trying out Nuxtent!

**Comment by hackuun** [comment]
Sorry, but I still don't get it. 
First, demo is still broken, even tho you told it's fixed.
Second, I read Nuxtent docs, but I still have no idea how to fix this template.

**Comment by hackuun** [comment]
This doesn't work

```
module.exports = {
  content: {
    permalink: ':slug',
    page: '/_content',
    generate: [ // for static build
      'get', 'getAll'
    ],
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://localhost:3000'
      : 'http://localhost:3000'
  }
}
```

This doesn't work too

```
module.exports = {
  content: {
    permalink: ':slug',
    page: '/_content',
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'https://nuxtent-template.now.sh'
      : 'http://localhost:3000'
  }
}
```

**Comment by alidcast** [comment]
I need more information on what command you are running and what error you are getting to know what problems *you* are running into.  I said it works because it works for me but I'm only one person.

**Comment by ghost** [comment]
#6 I didn't view this issue, I linked my issue, me too it doesn't work.

**Comment by ghost** [comment]
eventually it works like that : 

```
module.exports = {
  content: {
    permalink: ':slug',
    page: '/_content',
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'https://nuxtent-template.now.sh'
      : 'http://localhost:3000'
  }
}
```


edit : the generate works, but when I got to the page /hello-world, I always have the message : 
`render function or template not defined in component: anonymous
`

**Comment by alidcast** [comment]
See #6. Thanks for narrowing it down @STnetwork
