### ISSUE TITLE
Fails on windows with TypeError

### ISSUE THREAD

**Issue by nerdoza** [nuxt-community/content-template#8]
Getting error on fresh install
```
 WARNING  Compiled with 1 warnings                                                                                                                                                             16:55:03

 warning  in ./content/HelloWorld.comp.md

Module build failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at getSection (C:\Users\Bayss\Downloads\my-site\node_modules\nuxtent\dist\loader.js:107:33)
    at Object.module.exports (C:\Users\Bayss\Downloads\my-site\node_modules\nuxtent\dist\loader.js:54:19)

 @ ./content \.comp\.md$
 @ ./.nuxt/dist.plugin.238a682c.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?reload=true ./.nuxt/client.js
```
This is on a completely new/fresh install following the basic setup instructions.

System is Windows 10 (x64), Node 8.3.0, npm 5.3.0, vue-cli 2.8.2.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-template/issues/c10">#c10</a>)</em></sub></div>

**Comment by dakebl** [comment]
I've had the same issue. I've been trying to get this running all day, to no avail. Any ideas @alidcastano ?

**Comment by nerdoza** [comment]
Looks to be related to https://github.com/nuxt-community/nuxtent-module/issues/34.

**Comment by alidcast** [comment]
Sorry for delay with this issue, I've been without a computer the last two weeks and thus limit time to work on this, but will be in position to look into this soon.

Yes, @bayssmekanique if you're using recent nuxt, it's likely a problem with markdown components.

**Comment by guylyons** [comment]
i've also run into the type error which seems to be coming from axios.js. i'm running node 8.0.0, npm 5.4.1, macOS 10.12.6

```
Nuxt.js Error:

TypeError: inject is not a function
    at module.exports.__webpack_exports__.default (.nuxt/axios.js:138:2)
    at _callee$ (.nuxt/index.js:117:10)
    at tryCatch (/Users/guylyons/github/yugsnoyl/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/guylyons/github/yugsnoyl/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/guylyons/github/yugsnoyl/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/babel-runtime/helpers/asyncToGenerator.js:17:0)
    at server-bundle.js:239:13
    at <anonymous>
```

my issue may be separate from this thread, but seemed it might be relevant.

**Comment by ghost** [comment]
@guylyons same issue on a fresh install here as well. Checked the files and indeed the inject function is undefined. Commenting it out resolves the issue, but then $axios is missing from the context, leading to further issues.

I would have expected .nuxt/axios.js:137 to be responsible for injecting $axios into the context, but that's not the case.

**Comment by darisi** [comment]
Updating Nuxt to **rc11** should solve the problem.

**Comment by guylyons** [comment]
@darisi this did end up working for me, upgrading to rc11, thank you.

To note: I did however have to `npm i webpack webpack-dev-server html-webpack-plugin` to get `npm run dev` to work correctly.

But now all appears to be working great. 😀
